### ISSUE TITLE
Do unlocated feature check sooner

### ISSUE THREAD

**Issue by willwhite** [mapbox/cardboard#110]
The unlocated feature check runs [immediately before writing a feature](https://github.com/mapbox/cardboard/blob/373570aca340eb2c9c2bd7854e6a9a06c6fffd97/index.js#L73-L77) and could potentially after some features have already been written. It should be possible to catch this problem before any features have been written and fail the entire call.

**Comment by rclark** [comment]
Fixed as of https://github.com/mapbox/cardboard/pull/119
