### ISSUE TITLE
Generated documentation with dox and doxme

### ISSUE THREAD

**Issue by willwhite** [mapbox/cardboard#123]

**Comment by jfirebaugh** [comment]
Can you use [documentationjs](http://documentationjs.github.io/) instead of dox / doxme?

**Comment by willwhite** [comment]
Happy to use whatever makes the most sense. @jfirebaugh any reason to select one over the other?

**Comment by jfirebaugh** [comment]
documentationjs is our (well mainly @tmcw's) home-grown effort at building a full modern JSDoc ecosystem. Would be great to adopt and standardize it for all our JS API documentation.

**Comment by willwhite** [comment]
:+1: I selected doxme based on a recommendation from @tmcw that https://github.com/mapbox/color-ops was the "state-of-the-art" in terms of tests and documentation - it uses doxme and was also aiming for consistency.

@tmcw agree that we should use documentationjs instead?

**Comment by tmcw** [comment]
@willwhite yep, only recently has documentationjs become stable enough to be recommended instead of dox.

**Comment by willwhite** [comment]
:+1: thx it looks amazing. Excited to play with it.

**Comment by rclark** [comment]
Started exploring in https://github.com/mapbox/cardboard/tree/documentation-js
