### ISSUE TITLE
Store number of edits in the metadata

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/cardboard#160]
A count of the number of edits would be helpful when trying to decide if you need to do a large recalculation of something derived from datasets stored in cardboard. While this won't keep copies of different versions of the dataset it will let users know if their derivative of the data is behind the data itself and will also let developers know if one derivative is from newer data than another one. 

To do this I think we'd just want to update [metadata.adjustProperties](https://github.com/mapbox/cardboard/blob/1d1238b736ab63e3433df902d11234169a05d1a9/lib/metadata.js#L160) and [metadata.defaultInfo](https://github.com/mapbox/cardboard/blob/1d1238b736ab63e3433df902d11234169a05d1a9/lib/metadata.js#L73)

I'm not 100% sure how dynamo works with add on properties that haven't been created yet, so this might require a migration for existing datasets.

**Comment by rclark** [comment]
This would just be a continuously incrementing counter then? And then derived products would keep track of the edit count at which they were spawned from the dataset?

This would be possible to begin implementing in an existing table without any data migration.

**Comment by mcwhittemore** [comment]
> And then derived products would keep track of the edit count at which they were spawned from the dataset?

Yep.
