### ISSUE TITLE
Retry unprocessed items

### ISSUE THREAD

**Issue by rclark** [mapbox/cardboard#170]
Currently if cardboard makes a batch write request to DynamoDB, and unprocessed items are returned [cardboard does not attempt to retry those items](https://github.com/mapbox/cardboard/blob/master/lib/batch.js#L65-L77). This "error" may or may not be handled well downstream.

The untagged, master branch of dyno [contains new functions](https://github.com/mapbox/dyno/pull/119) intended to do this retrying for you. We should try it out here in cardboard.

cc @mcwhittemore

**Comment by mcwhittemore** [comment]
@rclark unprocessed items are from dynamo rate limits right? Won't retrying this just result in the same result?

**Comment by rclark** [comment]
Unprocessed items are from throughput limiting or "internal server errors". The suggestion from DynamoDB docs is to always retry unprocessed items with exponential backoff. 

Come to think of it, the new functions in dyno **don't backoff**, but they should [right about here](https://github.com/mapbox/dyno/blob/master/lib/requests.js#L135).
