### ISSUE TITLE
Add support for GeometryCollections

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/cardboard#172]
https://github.com/mapbox/cardboard/blob/master/lib/utils.js#L82-L83 stops `GeometryCollections` from being saved. What is the reason behind not saving these?

**Comment by rclark** [comment]
GeometryCollections are a very serious can of worms for spatial indexing and retrieval. Let's keep them in mind though as we talk through #178

**Comment by tmcw** [comment]
Yeah, GeometryCollections are tough. I'd be happy with a better error message and potentially GeometryCollection support in the future.
