### ISSUE TITLE
cardboard.putSizeCheck

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/cardboard#174]
Currently cardboard.put will always write if the feature provided is valid. I have a use case where I want to stop the feature from being written if the change is size between the old version and the new version is greater than x. I think cardboard can provide this check using ConditionExpression on its putItem request, but there would need to be a way to pass this value in. 

`chardboard.putSizeCheck` seems like a very specific use case, maybe there are other kinds of things people might want to stop writes on?

**Comment by rclark** [comment]
[I think this would work?](https://github.com/mapbox/cardboard/blob/81450a2880c909e1cedf070c569680e299d13232/index.js#L482-L491)

**Comment by mcwhittemore** [comment]
I'm pretty sure that is equivalent to `dataset.size + new.size` which works for creates but for updates you need `dataset.size + new.size - old.size`.

Though, looking over this again, we'd need to use updateItem rather than putItem to get this to work.

**Comment by rclark** [comment]
I think that there is reason to consider breaking the `.put` function into a `.create` and an `.update`. You'd need this in order to compare pre- and post- updated feature sizes, and also #139 will require this. As-is we can't do it without adding a pre-put `.getItem` request, right?

With the current functions, using `dataset.size + new.size` you'll run the risk of blocking an update to an existing feature when your dataset is already near the size limit. This will be an obvious problem for datasets with a few, very large features, but practically imperceptible for datasets with many small features. Is it a valid stopgap?

**Comment by mcwhittemore** [comment]
> As-is we can't do it without adding a pre-put .getItem request, right?

If the old value was provided you could do an optimistic update and than revert the change. Most of the time it would only take one request, sometimes it would take two.

> Is it a valid stopgap?

Maybe. If the only other way we're good with doing this is breaking put up into create/update than it will do but it will introduce bugs. I guess they are known bugs which is nice.

**Comment by rclark** [comment]
> If the old value was provided you could do an optimistic update and than revert the change.

Not sure I follow -- do you mean that the old value would be provided by an optimistic .updateItem request with ReturnValues: `ALL_OLD`? How else would the old value be provided?

**Comment by mcwhittemore** [comment]
@rclark that is what I'm thinking. `put` uses `putItem` we'd need to change the ReturnValues to `ALL_OLD`. What I'm not sure about is how we'd communicate this value to the callback. There are a bunch of ways we could do it, but they all feel like hacks.

**Comment by rclark** [comment]
Gotcha. I didn't realize that you could specify ReturnValues on putItem requests.

The ideal case would be to limit the write via condition expression, but I'm not sure I know how you'd write that expression. "Only write if the difference between old & new size is less than X."

Short of that, I think that the optimistic write you proposed results in the smallest number of requests. But it is still scary in the distributed system:

- request 1 puts feature A with size 10
- request 2 puts feature A with size 200, learns that it has blown past the desired threshold, gets ready to rollback....
- request 3 puts feature A with size 12, which is fine
- request 4 (rollback from request 2) returns feature A to the initial state, and we've lost the info from request 3

**Comment by mcwhittemore** [comment]
> I'm not sure I know how you'd write that expression

I think you'd write it so that if `old.size > x` the request will go through. `x` would be `dataset.size + new.size - threshold`. `old.size` would need to default to 0 if its a create.

All of that said, the multiple requests edges case is pretty bad too so I'm going to go with `dataset.size + new.size` block for now and deal with this later.

**Comment by mcwhittemore** [comment]
Thi is not possible with batchWriteItem... :(. Closing for now.
