### ISSUE TITLE
Better hash indexes

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/cardboard#184]
With our current key structure `{dataset}` is the HASH and `id!{featureid}` is the RANGE. This has worked for us for a while, but recently we've noticed that we get hot indexes that can cause write failures. The root of this problem is that there can be 1000s of writes per dataset very quickly when a user is adding a lot of features.

Let's use this ticket to explore other indexing options.

/cc @mick @rclark

**Comment by rclark** [comment]
I did some experiments in the past where you store large features as hash-only, and small index records under an aggregate hash key. To pull all the features then, you would:

- query the aggregate to get a list of hash keys for each full feature
- batch get all the features

This leads to a tremendous increase in read throughput consumed, especially when full features are small. Batch get requests do not aggregate returned size and charge you on that sum like queries do.

It can also get a little harder to paginate, but not insurmountably. The first query can return a ton of features that you need to batch get, but you have no idea how large the resulting "page" will be once you've batch got all the full features.

On the flipside you get much much better write throughput utilization, and writes are much more expensive than reads. $0.0065 gets you 200kb of reads per hour, while it gets you 10kb of writes. Double that in a situation like ours where you write to two databases and only read from one at a time, and writes are 40x more expensive than reads (O_o did I do that math right?)

**Comment by mcwhittemore** [comment]
@rclark `feature` in your first sentence is not a GeoJSON feature, right? You're talking about documents here?

**Comment by rclark** [comment]
I did these experiments in a table completely separate from cardboard. But the idea is the same:

- every "full" record has an id as the dynamo hash key
- index records share a hash key and the range is a pointer to a "full" record's id
- query the index hash key, then batch get each "full" record

**Comment by mcwhittemore** [comment]
Just making sure I get how this translates to cardboard. In the `full` table the hash key would be `{dataset}!{feature}` and in the `index` table the hash key would be `{dataset}` and the range key would be `{feature}`. Is that right?

Does this mean that a partition of dynamo gets hot based on the number of bytes written to it, and not just the number of writes?

**Comment by mcwhittemore** [comment]
Just spit-balling an idea here. I think this idea might require transactional writes...

Currently, we have a `metadata!{dataset}` record. This is used to store data about the dataset such as its size, the number of updates it's seen and the number of features it has.

Knowing the number of features means that we could also have a page index that looks something like `page!{dataset}!{page}`. This document would be a list of features. Each time an update/put or delete came into cardboard we'd read the dataset metadata document and compute the number of pages. Then we'd hash the feature id to compute which page to put it into.

The problem that arises is that we'd need to repaginate the features anytime a page got too big (a hot partition) or the number of features in the dataset got to the max number of features we wanted in a page. I think repaginating would require us to lock the dataset from all list and write requests.

Locking might be doable with the metadata document (which we have to get for every read to know the number of pages for hashing).

A side benefit of this change would be that users could know the number of pages in their dataset. You wouldn't know the number of features in a page though and could have empty pages...

**Comment by rclark** [comment]
> Does this mean that a partition of dynamo gets hot based on the number of bytes written to it, and not just the number of writes?

Yes -- 1 write request that is less than 1kb consumes 1 write units, while 1 write request for 11.5kb consumes 12 write units. You can see that this still doesn't get you away from "hot" partitions entirely -- there's literally no way to aggregate records in dynamodb without encountering this issue, all you can do is minimize it.

What you're proposing wrt the metadata record would place huge write loads on that single database record, no? Every feature write would involve at least one write to the metadata record, plus some reading. The general idea though is to precompute pages at write time and remove the need to query?

**Comment by mcwhittemore** [comment]
> The general idea though is to precompute pages at write time and remove the need to query?

I'm trying to think of no querying as a cool side effect. My main thought is that if we design around only HASH keys we should have fewer hot partitions.

> Every feature write would involve at least one write to the metadata record, plus some reading.

On a PUT, dynamo would need return the old value so we could know if we needed to insert it into the page. On a delete, you'd need to do the write to the page. On bulk write operations, you'd probably need to do one write per page (via an UpdateExpression). This means in any one request each partition should only get written to once.

> 1 write request that is less than 1kb consumes 1 write units, while 1 write request for 11.5kb consumes 12 write units

Oh. Cool. I didn't know how that math worked.

So a dataset that is 3MB would be 3000 write units?

**Comment by rclark** [comment]
> So a dataset that is 3MB would be 3000 write units?

Yes, if it was being written in a single request in a single second, which it wouldn't likely be.

> if we design around only HASH keys we should have fewer hot partitions.

This is true as long as you *also* don't have any individual hot documents. It sounds to me like you're trading out a hot hash key with more than one record for a hot record with a single hash key. But maybe I'm just not quite following the concept.

Also keep in mind that an UpdateItem request to a 500kb record that adds 1kb of data to the record costs 501 write units.

**Comment by mcwhittemore** [comment]
> keep in mind that an UpdateItem request to a 500kb record that adds 1kb of data to the record costs 501 write units.

meh. Just read through the AWS docs hoping to see that UpdateExpressions were changed based on what you changed... They are not. 

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithTables.html#ProvisionedThroughput

OK... Time to think of a new idea about how to do this.

**Comment by mcwhittemore** [comment]
From a hot partition POV, we'd ideally have a HASH key of `{dataset}!{feature}` and no RANGE key. This is as unique and consistent as we can be. The problem is that we have no way to query if we do this and we'd find ourselves scanning all the time.

Our two current functions that use query are `cardboard.list` and `cardboard.bbox`.

Leaving `cardboard.bbox` to its out ticket, `cardboard.list` has some warts. Pages can be empty, sort isn't possible, order isn't clear, pages have no clear size. While these warts are overcomeable by end users, it would be nice if they weren't there are all.

The problem with this is that we'd need to write twice for most writes to keep these listing documents in sync and that if two writes happen at the same time we run into a clash.

That said, we have DynamoDB Streams so we can avoid the race condition by configuring the stream to only run one working at a time. (I think that can be done). With this trick the problem becomes making sure our listing pages don't run into the hot partition problems we're trying to avoid with this ticket. Here again, DynamoDB Streams might save us. By changing the number of changes per job the stream works with we reduce the number of writes for these indexes by a lot (real numbers needed).

All of that said, it would introduce a downside. Because we'd be using streams to create our listing indexes there will be a lag between pushing and pulling. Personally I think this might be worth it. What do others think?

**Comment by rclark** [comment]
I'd think I would start like this:

hash | range | data
--- | --- | ---
dataset1!feature1 | - | geobuf
dataset1!feature2 | - | geobuf
dataset2!feature1 | - | geobuf
dataset1 | feature1 | 
dataset1 | feature2 | 
dataset2 | feature1 | 

Direct cardboard function calls to write would write feature records. DynamoDB stream would fill in the dataset index records. Those indexes can get hot, but it gets a little bit harder because you never write large objects to those hot hashes. Separating the index into multiple records as opposed to just one helps insure you don't have any confusion with concurrent updates to a dataset index.

Like you say, it'll be important that we have our DynamoDB stream writing the index records as fast as possible. I think success would be a <1s delay in getting any feature into the index. For that reason we'd definitely want to max out the number of records any single trigger invocation could consume from the stream.

**Comment by mick** [comment]
>  we'd ideally have a HASH key of {dataset}!{feature} and no RANGE key. 

Yes!  I think it makes a lot of sense to record the feature write as fast as possible, then deal with indexing. 

> All of that said, it would introduce a downside. Because we'd be using streams to create our listing indexes there will be a lag between pushing and pulling. Personally I think this might be worth it. What do others think?

Yeah, but otherwise we have a hard limit on how fast we can ingest data for a dataset. If a dataset is being heavily written to I think it will be ok for have a little lag on the indexing.

Why do this in the same table?  You'll still get hot partitions with the index and the features in the same table that will slow down some portion of feature writes that happen on the same partition. Why not put the index in another table or even in ES if that works out?

**Comment by rclark** [comment]
> Why do this in the same table?

No reason really. There's management overhead involved in each table we provision but it is manageable. Doing the dataset index in a separate dynamo table might be a good approach to weigh against ES as we push there for a spatial index.

**Comment by mcwhittemore** [comment]
I like this plan!

**Comment by mcwhittemore** [comment]
An upside to using a separate table is that it could be used by other kinds of customing indexing operations (aka, bbox).

**Comment by rclark** [comment]
> To be honest, this seems good to me. It is better to fail hard that have a partial success.

That's the whole point though -- if writing to the table is throttled by the speed at which we can write to the GSI, we're in exactly the same position we're in now. The point of migrating to a primary index where each feature's HASH is unique is that we can write to that table much faster than we can write to an index that aggregates features by dataset or quadkey. 

If we're going to do this at all, we have to be content that the listing / spatial indexes will be more eventually consistent than they are now. DynamoDB streams help us guarantee that every feature will get written to the index, since failures will alarm loudly and prevent further stream processing -- we will get the memo and fix it somehow to keep data flowing.

**Comment by jakepruitt** [comment]
So I did some benchmarks to get a general idea of the cardboard latency we're dealing with so we can measure exactly how different alternatives play out, and whether the gains to writes are worth the costs in listing latency/eventual-consistency. All tests were done using https://github.com/mapbox/cardboard-hammer.

### Write Hammer

I created a script that just repeatedly hammers cardboard directly with a bunch of `cardboard.put`'s with the same single-feature geojson with an adjustable concurrency and timeframe. The [feature I used](https://github.com/mapbox/cardboard-hammer/blob/master/test/data/blah.geojson) was a 2k feature that geobuf's down to 999 bytes, which is about the average feature size in Cardboard. Also note I was using `coredb-staging-cardboard` for all of these tests, which has 100 read and write capacity, 100 write cell capacity and 10 read cell capacity.

**Burst throughput**

One good sign initial tests showed was that it was impossible to throttle cardboard when only 5s of writes were thrown at the table. For a 5s test I was able to get `546 req/s` of writes with concurrency 150:

```bash
$ ./bin/hammer write test/data/blah.geojson -c 150 -t 5s

Size: 2158
Writes: 2730
Time: 5000
Concurrency: 150
Req/s: 546
Min Latency: 200
Avg Latency: 276.90439560439626
Max Latency: 1691
Throttles: 0
```

This (hopefully) means that if traffic is rather inconsistent for the datasets unpacker, it should be able to handle a geojson file with 2730 2KB-sized features without throttling the database.

**Sustained writes**

When the time was increased closer to 5 minutes, I could cause quite a few write thottles depending on how much concurrency I gave the hammer. I found the sweet spot for concurrency was around `35`, which resulted in a consistent traffic of about `100 req/s` with very few throttling events:

```
$ ./bin/hammer write test/data/blah.geojson -c 35 -t 5m

Size: 2158
Writes: 30023
Time: 300000
Concurrency: 35
Req/s: 100.07666666666667
Min Latency: 38
Avg Latency: 343.45704959531133
Max Latency: 27211
Throttles: 34
```

### Write-and-list hammer

To get an idea of what we're sacrificing by moving to the lambda-based system, I created another hammer that writes a feature and then polls `cardboard.list` until it gets the feature it just wrote. This script was much more prone to throttles on the read side, but I saw no sign of eventual consistency forcing multiple reads. The average latency I got in reads was usually between `700 ms` and `2000 ms` depending on how many sockets my local machine was able to expend:

```
$ ./bin/hammer write-and-list test/data/blah.geojson -c 100 -t 5s

Results:

Size: 2158
Successes: 129
Time: 5000
Concurrency: 100
Min Tries: 1
Avg Tries: 1.0000000000000016
Max Tries: 1
Min Time To List: 435
Avg Time To List: 1831.7209302325582
Max Time To List: 4345
Read Throttles: 0
```

```
./bin/hammer write-and-list test/data/blah.geojson -c 5 -t 5m                                                                              

Results:

Size: 2158
Successes: 764
Time: 300000
Concurrency: 5
Min Tries: 1
Avg Tries: 1.0000000000000129
Max Tries: 1
Min Time To List: 123
Avg Time To List: 1794.5785340314123
Max Time To List: 31469
Read Throttles: 2
```

I think the latency here is not indicative of anything except how slow my personal wifi is, but you can tell that it's under 2s. Hopefully we'll be able to keep the same eventual consistency number, and not blow up the latency for the same level of concurrency.

Will report back with numbers on hash-only-lambda-indexing table soon.

**Comment by rclark** [comment]
> I saw no sign of eventual consistency forcing multiple reads

This is expected given the existing system -- no lamba, just GSIs. The write-then-read hammer will only be useful after we build a table with an eventually consistent index fed via streams/lambda. I think that this is the way we can assess what we sacrifice by switching to an index like this:

- how much faster can we write features?
- whats the correlation between the speed we write and the index latency?
- is it acceptable?

**Comment by mcwhittemore** [comment]
> The feature I used was a 2k feature that geobuf's down to 999 bytes, which is about the average feature size in Cardboard. Also note I was using a cardboard table which has 100 read and write capacity, 100 write cell capacity and 10 read cell capacity.

> ...

> I found the sweet spot for concurrency was around 35, which resulted in a consistent traffic of about 100 req/s with very few throttling events:

100 req/s second matches the write cap of the table so this makes a lot of sense.

> For a 5s test I was able to get 546 req/s of writes

This is crazy. My guess is that this is caused by latency in the AWS rate limiter and thus I suspect that this is something that could/will change. Rate limiters are pretty hard to get right without costing too much overhead. 

@jakepruitt it might be interesting to try a series of bursts to see what the effect on the AWS rate limiter would be. This knowledge would help us give recommendations to end users on how long their rate limiter should track usage for. Does it need to be per second? Or can it be every 5 seconds?

**Comment by rclark** [comment]
> My guess is that this is caused by latency in the AWS rate limiter

There's explicit documentation that you can burst over provisioned capacity for short periods of time. See http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GuidelinesForTables.html#GuidelinesForTables.Bursting

**Comment by mcwhittemore** [comment]
Wow. I'm not sure if I like knowing that there is a five-minute semi-roll-over on capacity. It's too tempting to think about how to use it even though the next sentence in the docs more or less tell you to not use this.

**Comment by mcwhittemore** [comment]
Here is a comparison of the `cardboard-hammer` scripts for one table (@jakepruitt's results from above) and for two tables.

The two table results using these shas

- [cardboard](https://github.com/mapbox/cardboard/pull/186/commits/0a0263a8e56702d06bc51497e2b89adbc495c642)
- [cardboard-list](https://github.com/mapbox/cardboard-list/pull/1/commits/c0384e30e57652517fc5c464e94e8596b4246a50)
- [cardboard-hammer](https://github.com/mapbox/cardboard-hammer/pull/2/commits/1abe5d6df455bb192d5e27f619c3586074737aac)


**$ ./bin/hammer write feature.geojson -c 150 -t 5s**

First off, anything under 5s is still good. As expected.

| Data Point |  One Table | Two Tables |
| --- | --- | --- |
| Size | 2158 | 2158 |
| Writes | 2730 | 2211 |
| Time | 5000 | 5000 |
| Concurrency | 150 | 150 |
| Req/s | 546 | 442.2 |
| Min Latency | 200 | 280 |
| Avg Latency | 276.90439560439626 | 336.03663500678437 |
| Max Latency | 1691 | 782 |
| Throttles | 0 | 0 |

**$ ./bin/hammer write feature.geojson -c 35 -t 5m**

For longer hammers we still see throttles, but not as much. This result doesn't really tell us much though as the concurrency is set to have the one table config error as little as possible which would also result in low errors for the two table config. We'll need to run and record more concurrency to see what real improvements we have here.

| Data Point |  One Table | Two Tables |
| --- | --- | --- |
| Size | 2158 | 2158 |
| Writes | 30023 | 27222 |
| Time | 300000 | 300000 |
| Concurrency | 35 | 35 |
| Req/s | 100.07666666666667 | 90.74 |
| Min Latency | 38 | 95 |
| Avg Latency | 343.45704959531133 | 382.7313202556785 |
| Max Latency | 27211 | 28853 |
| Throttles | 34 | 3 |


**$ ./bin/hammer write-and-list feature.geojson -c 100 -t 5s**

Before there was no pause between listing requests. Since the one table result completes this in one request, I think it is safe to have added a 10ms pause between requests. This way we lower read cap usage as the table gets bigger.

Listing time has improved! Which makes no sense because the number of requests before getting the desired feature has tripled. It could be that I have much better network time than @jakepruitt did. It also could be I am returning ids and not full features which speeds up response time. Those two difference aside, the change in the number of requests is as expected.

We might want to run this test again on both table configs, but changing how we track time to be from after the put is done to before the list request is made. For the one table config, this will result in the request time being zero and I think it will give us a clearish idea of how long we need to wait before the feature is moved to the second table in the two table config.

| Data Point |  One Table | Two Tables |
| --- | --- | --- |
| Size | 2158 | 2158 |
| Successes | 129 | 265 |
| Time | 5000 | 5000 |
| Concurrency | 100 | 100 |
| Min Tries | 1 | 1 |
| Avg Tries | 1 | 3.113207547169819 |
| Max Tries | 1 | 6 |
| Min Time To List | 435 | 308 |
| Avg Time To List | 1831.7209302325582 | 990.7924528301888 |
| Max Time To List | 4345 | 2059 |
| Read Throttles | 0 | 0 |

**$ ./bin/hammer write-and-list feature.geojson -c 5 -t 5m**

This is more of the same. There is a drop in read throttles, which is too be expected as we're returning less data per read (just ids).

| Data Point |  One Table | Two Tables |
| --- | --- | --- |
| Size | 2158 | 2158 |
| Successes | 764 | 1130 |
| Time | 300000 | 300000 |
| Concurrency | 5 | 5 |
| Min Tries | 1 | 1 |
| Avg Tries | 1.0000000000000129 | 2.1061946902654536 |
| Max Tries | 1 | 4 |
| Min Time To List | 123 | 418 |
| Avg Time To List | 1794.5785340314123 | 1022.0000000000003 |
| Max Time To List | 31469 | 2183 |
| Read Throttles | 2 | 0 |

**Comment by rclark** [comment]
> It also could be I am returning ids and not full features which speeds up response time.

To compare apples and apples, the 2-table list should return entire features. That means
- list ids from the index table
- batch get features from the main table
- you're done when you've got them all

I'm surprised you got any write throttling in the 2-table situation. What were the table's capacity values?

**Comment by mcwhittemore** [comment]
The tables have the same read/write cap as @jakepruitt's test tables. 100. Right now I'm looking to see what write/read capacity it would take to get a 150c/5m test to work without throttles.

I'll update the listing test to also fetch the features. Should take the same number of tries, but it should also take longer. One question will be if we see more read throttles doing this.

**Comment by mcwhittemore** [comment]
**./bin/hammer write feature.geojson -c 150 -t 5m**

OK. I just ran the write test on the two table config with 150c/5m at a few different capacity limits.

The good news is that increasing capacity, decreasing the number of throttles and increases the writes per second that we can do.

The bad news is that by speeding up request time, we also invite more requests and these additional requests create throttles. This is a problem of using concurrency vs a set number of requests a second. We should confirm that this does not happen with the one table model. If it does not, I think the two table model proves it scales pretty well.

|Data point | 100 | 200 | 300 | 400 |
| --- | --- | --- | --- | --- |
| Writes | 30345 | 59703 | 75049 | 112437 |
| Req/s | 101.15 | 199.01 | 250.16 | 374.79 |
| Min Latency | 91 | 90 | 91 | 113 |
| Avg Latency | 1440.61 | 736.70 | 588.99 | 397.65 |
| Max Latency | 29275 | 28950 | 28271 | 28276 |
| Throttles | 542 | 320 | 194 | 40 |

**Comment by rclark** [comment]
> problem of using concurrency vs a set number of requests a second

Yeah -- a better system might spawn several concurrent processes which each make requests at a fixed rate.

**Comment by mcwhittemore** [comment]
Yea. It would also be nice to have a bench script that starts at one request a second and doubles the number of r/s every minute. It would stop when it first saw a throttled request. That said, I don't think we need this to know that two tables scale better than one.

**Comment by mcwhittemore** [comment]
Per @rclark's request, here are the updated results on the longer list operation. This time the two table config also fetches the features.

**$ ./bin/hammer write-and-list feature.geojson -c 5 -t 5m**

| Data Point |  One Table | Two Tables |
| --- | --- | --- |
| Size | 2158 | 2158 |
| Successes | 764 | 374 |
| Time | 300000 | 300000 |
| Concurrency | 5 | 5 |
| Min Tries | 1 | 1 |
| Avg Tries | 1 | 1.975935828877012 |
| Max Tries | 1 | 2 |
| Min Time To List | 123 | 959 |
| Avg Time To List | 1794.5785340314123 | 3565.366310160426 |
| Max Time To List | 31469 | 15281 |
| Read Throttles | 2 | 0 |

As expected we see the average latency increase. Unexpectedly, we also see the number of tries decrease. Thinking this over a bit, it makes sense. Now that we load all of the features, the first request takes longer meaning there is a better chance the second request will result in the feature.

Another expectant result is that the max time is half that of the old max time. I'm going to assume that this is a difference in network speeds between @jakepruitt and myself.

**Comment by mcwhittemore** [comment]
I spent some time trying to prove that the two table config would scale where the one table would not. I need to run, but 600 concurrency looks the same across the two configs, which is not what I expected.

# ./bin/hammer write feature.geojson -c 600 -t 5m

## 200 read/write cap

**one table**

```
Size: 2158
Writes: 61485
Time: 300000
Concurrency: 600
Req/s: 204.95
Min Latency: 244
Avg Latency: 2826.9593071481004
Max Latency: 36269
Throttles: 1540
```

**two tables**

```
Size: 2158
Writes: 61335
Time: 300000
Concurrency: 600
Req/s: 204.45
Min Latency: 246
Avg Latency: 2861.2340751610004
Max Latency: 36113
Throttles: 1440
```

## 1500 read/write cap

**one table**

```
Size: 2158
Writes: 137031
Time: 300000
Concurrency: 600
Req/s: 456.77
Min Latency: 1155
Avg Latency: 1312.2629915858945
Max Latency: 2156
Throttles: 0
```

**two tables**

```
Size: 2158
Writes: 139354
Time: 300000
Concurrency: 600
Req/s: 464.5133333333333
Min Latency: 880
Avg Latency: 1290.0075491195573
Max Latency: 3858
Throttles: 0
```

**Comment by rclark** [comment]
First of all -- am I correct to assume that the writes in the two-tables system are *only* writing to the main table where there's a hash-only index? I can also assume that all writes are to a single dataset?

With those assumptions, I'm not sure your outcome is unexpected. At 200 read/write capacity and not a lot of data in either table, each table will have only one partition. That means that you've got 1 partition with 200 write capacity, and in either case, all the writes land on that partition.

Step up read and write to 1500 capacity, and I think that you'll have forced your table onto two partitions. At this point, each of those partitions are allocated 750 write capacity. In the old schema, all of your writes would fall onto one partition, while in the new schema your writes should be distributed between the two partitions.

So I think that you might see throttling in the old schema if you can get your req/s rate into the 750+ range, but the new schema should be ok.

**Comment by mcwhittemore** [comment]
> am I correct to assume that the writes in the two-tables system are only writing to the main table where there's a hash-only index?

The scripts write to the main table and lambda functions write to the list table.

> I can also assume that all writes are to a single dataset?

Yep

@rclark hmmm, I was thinking the number of partitions would be higher for the 1500 cap setups. What tool do you use to check this again?

What we're looking for here is a multi-partition situation where the one-table config fails and the two-table config does not fail. I'll try to push the limits a bit more, but we might need to move to bulk writing to create enough demand with one computer.

**Comment by mcwhittemore** [comment]
OK. I think this is pretty good proof that the two-table model scales where the first model does not. This last test leaves me with two concerns. One being that the request rate is very different and the second being that the new cardboard is retrying writes. You can see this in the very low `% of Throttles` stat, but a high number of throttles in the graph at the bottom.

The data below is from running at 600c/5m with a 10774kb feature. This feature is about 5 times bigger than the one we were using before.

| Data Point | One Table | Two Tables|
| --- | --- | --- |
| Writes | 32105 | 60159 |
| Req/s | 107.016 | 200.53 |
| Min Latency | 319 | 1060 |
| Avg Latency | 5444.709 | 2969.697 |
| Max Latency | 37730 | 43161 |
| Throttles | 2062 | 103 |
| % of Throttles | 6.422 | .171 |

While both configs throttle, % of writes that were throttled is very different. As mention above, this is in part because the two table model retries throttled events... I need to change that.

Looking at the consumed capacity of both configs we can see that the one-table config never reaches the 1500 cap mark while the two-table config is always above that mark. This is a good sign that the two-table config is scalable as its only throttling when the max capacity is being passed, where the one-table model is throttled without passing the max capacity.

For these screen shots, the spikes to the far right are what we car about.

**one table**
![image](https://cloud.githubusercontent.com/assets/1551510/21018530/30fe9e7e-bd3b-11e6-858e-b5f97ec33411.png)

**two tables**
![image](https://cloud.githubusercontent.com/assets/1551510/21018720/e2c81e0a-bd3b-11e6-83b9-cda423d81170.png)

Here are screen shots of the throttle rates for the two configs as well. Again, you can see here that the two-table model is being throttled a good deal, it's just handling it well.

**one table**
![image](https://cloud.githubusercontent.com/assets/1551510/21018496/0f126fa2-bd3b-11e6-9f42-ad9a0d93d877.png)

**two tables**
![image](https://cloud.githubusercontent.com/assets/1551510/21018741/fcf723e8-bd3b-11e6-8b58-482410ec0d53.png)
